language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
  allow_failures:
    - php: nightly
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
after_script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover